title: Jekyll Obsidian
description: A configurable website and documentation system built from Obsidian

website:
  source: 'website/jekyll-obsidian-docs'
  theme: 'minimal'
  repository: ""
  edit_branch: main
  html:
    slides/jekyll-obsidian: /slides/jekyll-obsidian/
  contacts:
    - label: GitHub
      url: https://github.com/wowfun
    - label: X
      url: https://x.com/wowfuna
  i18n:
    enabled: true
    locales:
      - en
      - zh-CN
  comments:
    enabled: true
    repository_id: R_kgDOTpvnAQ
    category: Blog comments
    category_id: DIC_kwDOTpvnAc4DCly_
  analytics:
    provider: cloudflare
    token: 39256861462445f681576be582afd9e4
