title: Jekyll Obsidian
description: A configurable website and documentation system built from Obsidian
lang: en

website:
  source: website/jekyll-obsidian-docs
  theme: minimal
  html:
    slides/jekyll-obsidian: /slides/jekyll-obsidian/
  contacts:
    - label: GitHub
      url: https://github.com/wowfun
    - label: X
      url: https://x.com/wowfuna
