title: My Site
description: ""
lang: en
url: ""
baseurl: ""

website:
  source: docs
  syntax_profile: ofm@1
  theme: minimal
  repository: ""
  edit_branch: main
  content:
    publish_by_default: []
    default_type: page
    directories:
      post:
        - blog
      doc:
        - docs
  features: {}
